namespace Nanuq.Common.Enums;

public enum ActivityTypeEnum
{
	AddKafkaServer = 1,
	RemoveKafkaServer = 2,
	AddKafkaTopic = 3,
	RemoveKafkaTopic = 4,
	AddRedisCache = 5,
	RemoveRedisCache = 6,
	AddRedisServer = 7,
	RemoveRedisServer = 8,
	AddRabbitMQServer = 9,
	RemoveRabbitMQServer = 10,
	AddRabbitMQExchange = 11,
	RemoveRabbitMQExchange = 12,
	AddRabbitMQQueue = 13,
	RemoveRabbitMQQueue = 14,
	AddAWSServer = 23,
	RemoveAWSServer = 24,
	AddSQSQueue = 25,
	RemoveSQSQueue = 26,
	SendSQSMessage = 27,
	AddSNSTopic = 28,
	RemoveSNSTopic = 29,
	PublishSNSMessage = 30,
	AddSNSSubscription = 31,
	AddAzureServer = 32,
	RemoveAzureServer = 33,
	AddAzureServiceBusQueue = 34,
	RemoveAzureServiceBusQueue = 35,
	SendAzureServiceBusMessage = 36,
	AddAzureServiceBusTopic = 37,
	RemoveAzureServiceBusTopic = 38,
	PublishAzureServiceBusMessage = 39,
	AddAzureSubscription = 40,
	RemoveAzureSubscription = 41,
}
